[[session]]
name = "main (Alma)"
path = "~/alma/main/"
startup_command = "git pull"
preview_command = "echo 'Main Alma directory'"


[[session]]
name = "nvim config"
path = "~/dotfiles/nvim/.config/nvim/"
startup_command = "nvim"

[[session]]
name = "tmux config"
path = "~/dotfiles/tmux/"
startup_command = "nvim .tmux.conf"
preview_command = "bat --color=always ~/dotfiles/tmux/.tmux.conf"

