[[session]]
name = "main (Alma)"
path = "~/alma/main/"
preview_command = "cat ~/.config/sesh/almamain.txt"

[[session]]
name = "nvim config"
path = "~/dotfiles/nvim/.config/nvim/"
startup_command = "nvim init.lua"
preview_command = "cat ~/.config/sesh/nvim.txt"

[[session]]
name = "tmux config"
path = "~/dotfiles/tmux/"
startup_command = "nvim .tmux.conf"
preview_command = "batcat -f -p ~/dotfiles/tmux/.tmux.conf"

