# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$kubernetes\
$directory\
$git_branch\
$git_state\
$git_status\
$character"""


right_format = """
$python\
$elm\
$nodejs\
$rust"""

[directory]
style = "bold blue"

[character]
success_symbol = '[ó°œ´](bold green) '
error_symbol = '[ï€](bold red) '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "italic bold green"


[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "bold purple"
conflicted = 'ğŸ³'
up_to_date = ''
untracked = 'ï”© '
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = 'ï£– '
modified = 'ï„ '
staged = '[+$count](green)'
renamed = 'è¥ '
deleted = 'ï€” '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "îœ¼ "
style = "bold cyan"

[nodejs]
disabled = true
