# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$character"""


right_format = """
$python\
$elm\
$nodejs\
$rust"""

[directory]
style = "bold green"

[character]
success_symbol = '[󰜴](bold green) '
error_symbol = '[](bold red) '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "italic bold blue"


[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "bold bright-green"
conflicted = ''
up_to_date = ''
untracked = ''
ahead = ' ${count}'
diverged = ' ${ahead_count}  ${behind_count}'
behind = ' ${count}'
stashed = ' '
modified = ' '
staged = '[ $count](green)'
renamed = ' '
deleted = '[ ](red) '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "
style = "italic cyan"

[nodejs]
disabled = true
